name: PR Tests

on:
  push:
    branches: 
    - master
  pull_request:
    branches:
    - master
jobs: 
  linter:
    name: Linter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --show-source --statistics
